### PR TITLE
fix: use WHATWG URL API to rewrite rootUrl correctly

### LINKED ISSUE #351: option rootUrl is not replaced correctly
#### Environment details

  - OS: `any`
  - Node.js version: `^12`
  - npm version: `^6`
  - `googleapis-common` version: `4.4.3`

#### Steps to reproduce

```javascript
const { GoogleApis } = require('googleapis');

const google = new GoogleApis({
  rootUrl: 'https://googleapis-endpoint'
});

// gmail API is used for example, it should happen to others as they share createAPIRequest()
const gmail = google.gmail({
  version: 'v1',
  rootUrl: 'https://googleapis-gmail-endpoint'
});

// ERROR in replacing URL! (list API is used for example, should happen to all as described above)
gmail.users.history.list({
  userId: 'me'
};
```

https://github.com/googleapis/nodejs-googleapis-common/blob/8032a85f88dc1ffd1c0b5bc054386fc1ef24af9e/src/apirequest.ts#L176-L177

There are 2 issues in handling `rootUrl`:

1. It is not clear which `rootUrl` take precedence, global vs API specific, and take note of sub point iii
   1. **_Global_**, set by `new GoogleApis(...)` (`gmail.context.google._options.rootUrl === 'https://googleapis-endpoint'`)
   2. **_API specific_**, set by `google.gmail(...)` (`gmail.context._options.rootUrl === 'https://googleapis-gmail-endpoint'`)
   3. **Note**: in current implementation, **_Global_** setting has no effect whatsoever
2. The usage of `options.url.slice` above causes issue, from my example code:

```javascript
// FAIL! with actual url === 'https://googleapis-gmail-endpoint/l/v1/users/me/history'
gmail.users.history.list(...);
// slice function returns 'l/v1/users/me/history', since,
// 'https://googleapis-gmail-endpoint'.length === 33, i.e. 'https://gmail.googleapis.com/gmai' sliced
```

### PR DESCRIPTION
**Pull request by yitomok**
Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [x] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/nodejs-googleapis-common/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [x] Ensure the tests and linter pass
- [ ] Code coverage does not decrease (if any source code was changed)
- [ ] Appropriate docs were updated (if necessary)

Fixes #351 🦕

### CODE REVIEW

**Comment by yitomok** [comment]
@googlebot I signed it!

**Comment by yitomok** [comment]
Not sure about that `0.01%` decrease...

File: src/apirequest.ts [hunk 1]
```diff
@@ -173,8 +171,9 @@ async function createAPIRequestAsync<T>(parameters: APIRequestParams) {
     parameters.context._options.rootUrl !== undefined &&
     options.url !== undefined
   ) {
-    const path = options.url.slice(parameters.context._options.rootUrl.length);
-    options.url = resolve.resolve(parameters.context._options.rootUrl, path);
+    const originalUrl = new URL(options.url);
+    const path = originalUrl.href.substr(originalUrl.origin.length);
+    options.url = new URL(path, parameters.context._options.rootUrl).href;
```
Comment (bcoe) [inline src/apirequest.ts:176]: small concern I have here, is that this approach would throw on an invalid URL, where as I believe the resolve would not:

```
> new URL('batman')
Uncaught TypeError [ERR_INVALID_URL]: Invalid URL: batman
    at onParseError (internal/url.js:256:9)
```

vs.,

```
> resolve('batman', '/batman')
'/batman'
```

Two options I see:

1. `console.warn`, and fallback to the original URL.
2. take this as a breaking change.

**Comment by bcoe** [comment]
> Not sure about that 0.01% decrease...

@yitomok probably a non issue when it's a delta this small.

File: src/apirequest.ts (hunk 1 above)
Comment (yitomok) [reply src/apirequest.ts:176]: From user perspective, it makes no difference when the invalid URL fail early as the new change, or inside the `.request<T>(..)` function. In my opinion I would consider option 2, take as a breaking change, because the error message is more specific than the original error inside `request`.

For example:
```javascript
var gmailApi = require('googleapis').google.gmail({ version: 'v1', rootUrl: 'batman' });

gmailApi.users.history.list({ userId: 'me' });
```

Old Error: `TypeError: Only absolute URLs are supported`
New Error: `TypeError [ERR_INVALID_URL]: Invalid URL: batman`

Let me know your thoughts @bcoe

Comment (yitomok) [reply src/apirequest.ts:176]: Hey @bcoe, let me know how should I move forward, thanks.

**Review by bcoe — APPROVED** [review]

**Comment by bcoe** [comment]
@yitomok thank you for the contribution. I've opted to land this as a breaking change, as discussed, which will allow us to roll it out carefully to `google-api-nodejs-client`.

**Comment by bcoe** [comment]
@yitomok this had been released, if you're so inclined, we'd happily take a patch to `google-api-nodejs-client`.
